seata:
  registry: # TC服务注册中心的配置，微服务根据这些信息去注册中心获取tc服务地址
    type: nacos # 注册中心类型 nacos
    nacos:
      server-addr: 127.0.0.1:8848 # nacos地址
      namespace: "" # namespace，默认为空
      group: DEFAULT_GROUP # 分组，默认是DEFAULT_GROUP
      application: seata-tc-server # seata服务名称
      username: nacos
      password: nacos
  tx-service-group: seata-demo # 事务组名称
  service:
    vgroup-mapping: # 事务组与cluster的映射关系
      seata-demo: default
  data-source-proxy-mode: AT
spring:
    application:
      name: seata-order-service
    datasource:
        username: root
        password: 123456
        url: jdbc:mysql://localhost:3306/seata_interview?serverTimezone=GMT%2B8
        driver-class-name: com.mysql.cj.jdbc.Driver
    # nacos config
#    cloud:
#      nacos:
#        config:
#          server-addr: 127.0.0.1:8848
#          # 配置文件后缀名为yaml
#          file-extension: yaml
server:
  port: 8092
